[General]
SyntaxVersion=2
BeginHotkey=32773
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=20
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=aec788cf-fcb0-4c5e-8aa1-0f9435c590a7
Description=家园种菜
Enable=0
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Attachment]
UEsDBBQAAgAIANAmu1DtYQSK5gAAADIBAAAIABEAytW78S5ibXBVVA0AB6DyzV408M1eNPDNXnPyNWJkAAMzINYAYh4gZgdiRgYJsPgfBkzQ0OdBELl5G1V3ugEZcenWXgEmManWjq4GVe0gkcpWVzsn/dJGl+wS95ou9/U7ek6e2zp7QcfJ04dySz3tnfW7poefOXuiqDIYqLh1cgCQLKsPmDC5/eS5zdW1RXcenPUPMzt7/ui02c1w6xatrQKKF1Z5Xbp8ztnd8Ojp1Tv3L+jq7qgBuwGOuiYUHD229+jxfUATAkPcP376YGpmZOeob2Ovl1/tBFSwbnv32Uvb9xxYO2funLv3rt19eP7Hz69nz524duN8bWsCUAEAUEsBAhcLFAACAAgA0Ca7UO1hBIrmAAAAMgEAAAgACQAAAAAAAAAgAICBAAAAAMrVu/EuYm1wVVQFAAeg8s1eUEsFBgAAAAABAAEAPwAAAB0BAAAAAA==


[Script]
SetSimMode 2

//收获
SaveMousePos 
Delay 50
RightClick 2
Delay 100
MoveTo 568, 504
Delay 50
LeftClick 1
Delay 100

//播种
RestoreMousePos 
Delay 50
RightClick 2
Delay 100
MoveTo 568, 504
Delay 100
LeftClick 1
Delay 100

//返回
RestoreMousePos

//种子
//MoveTo 378, 283 //选择种子
//LeftClick 1
//Delay 100
//MoveTo 280, 349	//选择包裹种子
//LeftClick 1
//Delay 100
//MoveTo 280, 389// 选择放入
//LeftClick 1
//Delay 100
//土壤
//MoveTo 378, 379 //选择土壤
//LeftClick 1
//Delay 100
//MoveTo 286, 437 //选中包裹土壤
//LeftClick 1
//Delay 100
//MoveTo 282, 482 //选择放入
//LeftClick 1
//Delay 100
//播种
//MoveTo 568, 504
//LeftClick 1
//Delay 100
