[General]
SyntaxVersion=2
BeginHotkey=121
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=767cb4fa-3662-4720-a932-18094c6e99e5
Description=大侠之路刷任务
Enable=0
AutoRun=0
[Repeat]
Type=1
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
'==========以下是按键精灵录制的内容==========
MoveTo 959, 696
Delay 100
LeftClick 1
MoveTo 1041, 556
Delay 100
LeftClick 1
'==========以上是按键精灵录制的内容==========
